# Generated by Django 5.1.2 on 2024-12-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumeratePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('output', models.CharField(max_length=1000)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WatermarkPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('watermark', models.FileField(upload_to='pdfs/')),
                ('output', models.CharField(max_length=1000)),
            ],
        ),
    ]
